apiVersion: v1
kind: Service
metadata:
  name: {{ include "emqx.fullname" . }}-headless
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}