replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: bloodstar/hexo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "local"

env:
  env1:
    name: "NODE_ENV"
    value: "production"
  env2:
    name: "HEXO_DEBUG"
    value: "false"