apiVersion: v2
name: qinglong
description: |
  Qinglong(青龙)是一个支持 Python3、JavaScript、Shell、Typescript 的定时任务管理平台,
  具有在线编辑脚本、定时执行、日志查看、文件管理等功能。适合需要自动化任务调度和脚本管理的用户使用。
version: 0.1.0
appVersion: "2.17.11"

home: https://github.com/whyour/qinglong
sources:
  - https://github.com/whyour/qinglong
  - https://hub.docker.com/r/whyour/qinglong
  
maintainers:
  - name: "whyour"
    email: "whyour@qinglong.com"
  - name: "Qinglong Team" 
    email: "team@qinglong.com"

annotations:
  "yunna.net/category": "Task Management"
  "yunna.net/category-zh": "任务管理"

keywords:
  - Qinglong
  - Automation
  - Task Management
  - Cron Jobs
  - Script Management

icon: "https://assets.yunna.net/i/2024/12/13/srhh08.png"