apiVersion: v2
name: uptime-kuma
description: |
  Uptime Kuma 是一个开源、轻量的自托管监控工具，支持对网站、服务器和 API 的正常运行时间进行实时监控，帮助用户快速了解服务的运行状况。它提供友好的用户界面、支持多种通知方式（如邮件、Telegram、Slack 等）以及历史记录追踪功能。
version: 0.1.1
appVersion: "latest"
home: https://github.com/louislam/uptime-kuma
sources:
  - https://github.com/louislam/uptime-kuma
maintainers:
  - name: "Louis Lam"
    email: "support@uptime-kuma.com"
annotations:
  "yunna.net/category": "Monitoring Tool"
  "yunna.net/category-zh": "监控工具"
keywords:
  - "Monitoring"
  - "Self-hosted"
  - "Uptime"
  - "Uptime Kuma"
icon: "https://assets.yunna.net/i/2024/12/13/sr129s.png"
