apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ubuntu-ssh.fullname" . }}-config
  labels:
    {{- include "ubuntu-ssh.labels" . | nindent 4 }}
data:
  setup.sh: |
    #!/bin/bash
    # 安装SSH服务和基础工具
    apt-get update && apt-get install -y openssh-server {{ join " " .Values.basePackages }} {{- if .Values.advanced.extraPackages }} {{ join " " .Values.advanced.extraPackages }} {{- end }}
    
    # 配置SSH
    mkdir -p /var/run/sshd
    echo 'root:{{ .Values.env.env1.value }}' | chpasswd
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin {{ .Values.env.env3.value }}/g' /etc/ssh/sshd_config
    
    # 创建额外用户
    {{- range .Values.ssh.extraUsers }}
    useradd -m -s /bin/bash {{ .username }}
    echo '{{ .username }}:{{ .password }}' | chpasswd
    {{- end }}
    
    # 应用额外SSH配置
    {{- range $key, $value := .Values.advanced.sshConfig }}
    echo "{{ $key }} {{ $value }}" >> /etc/ssh/sshd_config
    {{- end }}
    
    # 启动SSH服务
    /usr/sbin/sshd -D
