apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebrowser.fullname" . }}-config
data:
  .filebrowser.json: |
    {{ .Values.config.filebrowserJson | nindent 4 }}
  database.db: |
    {{ .Values.config.databaseDb | nindent 4 }}