name: PR Bot Response

on:
  workflow_run:
    workflows: ["PR Checks"]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    permissions:
      pull-requests: write
      issues: write
      contents: read
     
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run = context.payload.workflow_run;
            
            const prs = await github.rest.pulls.list({
              ...context.repo,
              head: run.head_branch 
            });
            
            if (prs.data.length === 0) {
              console.log('No related PR found');
              return;
            }
            
            const pr = prs.data[0];
            
            const logs = await github.rest.actions.downloadWorkflowRunLogs({
              ...context.repo,
              run_id: run.id
            });
            
            const errors = [];
            logs.data.toString().split('\n').forEach(line => {
              if (line.includes('::error::')) {
                errors.push(line.split('::error::')[1].trim());
              }
            });
            
            if (errors.length === 0) {
              console.log('No errors found in logs');
              return;
            }
            
            let comment = `## ❌ PR 检查失败\n\n`;
            comment += `### 失败项\n`;
            errors.forEach(err => comment += `- ${err}\n`);
            
            comment += `\n### 修复建议\n`;
            comment += `1. 请检查上述失败项\n`;
            comment += `2. 参考 [Chart开发规范](../docs/charts/STANDARDS.md)\n`;
            comment += `3. 使用 \`helm lint\` 验证语法\n`;
            comment += `4. 确保所有必需文件和字段完整\n\n`;
            comment += `修复后重新提交即可触发检查。`;

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: pr.number,
              body: comment
            });

            await github.rest.issues.addLabels({
              ...context.repo,
              issue_number: pr.number,
              labels: ['needs-fix']
            });