name: Repository Permissions

on:
  push:
    branches:
      - main
      - test
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  checks: read
  pull-requests: write
  issues: write
  contents: read
  statuses: read

defaults:
  run:
    shell: bash