name: PR Bot Response

on:
  check_suite:
    types: [completed]

jobs:
  bot-response:
    runs-on: ubuntu-latest
    if: github.event.check_suite.conclusion == 'failure'
    permissions:
      checks: read
      pull-requests: write
      issues: write
    
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.check_suite.pull_requests[0]?.number;
            
            if (!prNumber) return;
            
            const checkRunsResponse = await github.rest.checks.listForSuite({
              owner,
              repo,
              check_suite_id: context.payload.check_suite.id
            });
            
            const failedChecks = checkRunsResponse.data.check_runs
              .filter(run => run.conclusion === 'failure')
              .map(run => run.name)
              .join(', ');
            
            let comment = `❌ PR检查失败\n\n`;
            comment += `失败的检查项: ${failedChecks}\n\n`;
            comment += `请检查以下内容:\n`;
            comment += `1. Chart.yaml 是否包含所有必需字段\n`;
            comment += `2. values.schema.json 是否格式正确\n`;
            comment += `3. 模板文件是否语法正确\n`;
            comment += `4. 资源配置是否合理\n\n`;
            comment += `可参考文档: [Chart开发规范](../docs/charts/STANDARDS.md)\n\n`;
            comment += `修复后重新提交即可触发检查。`;
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: comment
            });

            // 添加标签
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: ['needs-fix']
            });